apiVersion: 1

datasources:
  - name: PostgreSQL-Translation-Analytics
    type: postgres
    access: proxy
    url: postgres:5432
    database: translation_analytics
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
    isDefault: true
    editable: true
